import java.util.*;
public class  CLASS_NAME{
  public static TYPE METHOD_NAME(TYPE VARIABLE_NAME) {
  }
}

/*
  [FUNCTION_OF_CODE]
  OPINION_ON_EXERCISE
*/

// THE VERSION BELOW IS THE BEST PRACTICE VERSION ON CODEWARS

/*
  [FUNCTION_OF_CODE]
  OPINION_ON_BEST_PRACTICE
*/
